<?php $this->layout('getting-started') ?>

<?php $this->start('gettingStartedContent') ?>
    <header>
        <h3>Install using a docker image</h3>
    </header>
    <p>If you plan to deploy shlink in a container-based infrastructure, you are probably in the simplest installation use case.</p>
    <p>You can just use the official <a target="_blank" href="https://github.com/shlinkio/shlink-docker-image">docker image</a>.</p>
    <p>Once deployed, you will need to run <code>docker exec -it shlink_container shlink api-key:generate</code> in order to generate the first API key.</p>
    <p>Finally access to <a href="https://app.shlink.io" target="_blank">shlink-web-client</a> and configure your server to start creating short URLs.</p>
    <blockquote>
        If you want, you can also host <a href="https://hub.docker.com/r/shlinkio/shlink-web-client/" target="_blank">shlink-web-client</a> yourself as a docker container.
    </blockquote>
<?php $this->end() ?>
