<footer id="footer">
    <ul class="icons">
        <li><a href="https://github.com/shlinkio/shlink" target="_blank" class="icon fa-github"><span class="label">Github</span></a></li>
        <li><a href="https://twitter.com/shlinkio" target="_blank" class="icon fa-twitter"><span class="label">Twitter</span></a></li>
        <li><a href="<?= $this->config('donate')['url'] ?>" target="_blank" class="icon fa-paypal"><span class="label">Donate</span></a></li>
    </ul>
    <p class="copyright">&copy; <?= date('Y') ?> Shlink. With <span class="fa fa-heart" title="love"></span> by <a href="https://www.alejandrocelaya.com" target="_blank">Alejandro Celaya</a> - Template from <a href="http://html5up.net">HTML5 UP</a></p>
</footer>
