<header id="header" class="big">
    <div class="content">
        <h1>Shlink</h1>
        <p>
            A self-hosted URL shortener.<br />
            Shorten URLs and serve them under your own short domain.
        </p>
        <ul class="actions">
            <li>
                <a href="<?= $this->url('template', ['slug' => 'getting-started']) ?>" class="button special icon fa-download">
                    Install
                </a>
            </li>
            <li><a href="#one" class="button icon fa-chevron-down scrolly">Learn More</a></li>
        </ul>
    </div>
    <div class="image"><img src="/images/shlink-logo-white.png"></div>
</header>
