<?php $slug = $this->current_route_params()['slug'] ?? '' ?>
<ul class="side-menu">
    <li>
        <a
            href="<?= $this->url('api-docs-section', ['slug' => 'error-management']) ?>"
            class="<?= $slug === 'error-management' ? 'selected' : '' ?>"
        >
            Error Management
        </a>
    </li>
    <li>
        <a
            href="<?= $this->url('api-docs-section', ['slug' => 'authentication']) ?>"
            class="<?= $slug === 'authentication' ? 'selected' : '' ?>"
        >
            Authentication
        </a>
    </li>
    <li>
        <a href="/swagger-ui/index.html" target="_blank">Endpoints</a>
    </li>
</ul>
