<?php $this->layout('layout') ?>

<?php $this->start('main') ?>
    <?php $this->insert('partials/small-header') ?>

    <section id="three" class="wrapper style3 special">
        <header class="major">
            <h2>API Docs</h2>
        </header>
    </section>
    <section id="one" class="wrapper">
        <div class="inner alt">
            <section class="spotlight text-only">
                <div class="content">
                    <div class="row">
                        <div class="3u 12u$(medium)">
                            <?php $this->insert('api-docs/partials/side-menu') ?>
                        </div>
                        <div class="9u 12u$(medium) side-menu-contents">
                            <?php if ($this->section('apiContent')): ?>
                                <?= $this->section('apiContent') ?>
                            <?php else: ?>
                                <header>
                                    <h3>REST API</h3>
                                </header>
                                <p>Shlink provides a REST API that can be used to integrate the short URLs management on any system or application.</p>
                                <p>All the requests return JSON-encoded responses and semantic status codes, so it should be easy to implement client apps that consume this API.</p>
                                <p>However, if an unexpected error occurs, the system could end returning HTML. To prevent this, always pass the <code>Accept</code> header with the <code>application/json</code> value.</p>
                                <p>This API supports <a href="https://en.wikipedia.org/wiki/Cross-origin_resource_sharing" target="_blank">CORS</a> (Cross domain), automatically generating the <code>Access-Control-*</code> headers and managing OPTIONS requests, so it can be consumed from web clients hosted on different domains.</p>
                                <p>Follow the documentation in order to see how to manage errors and perform requests correctly.</p>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </section>
<?php $this->end() ?>
