<?php $this->layout('layout') ?>

<?php $this->start('main') ?>
    <?php $this->insert('partials/small-header') ?>

    <section id="three" class="wrapper style2 special">
        <header class="major">
            <h2>Apps</h2>
        </header>
    </section>

    <section id="one" class="wrapper">
        <div class="inner alt">
            <section class="spotlight">
                <div class="image app">
                    <img src="/images/apps/shlink-web-client.png" alt="Shlink web client">
                </div>
                <div class="content">
                    <h3>
                        Shlink web client
                        <a class="external-app-link" target="_blank" href="https://github.com/shlinkio/shlink-web-client-angularjs/releases/latest">
                            <i class="fa fa-external-link"></i>
                        </a>
                    </h3>
                    <p>
                        Manage any number of Shlink servers with this AngularJS application.
                        <br>
                        See beautiful charts with your visit stats and easily create new short URLs.
                        <br>
                        You can self-host it yourself or try it from <a href="https://app.shlink.io" target="_blank">here</a>
                    </p>
                </div>
            </section>
        </div>
    </section>
<?php $this->end() ?>
