<?php $this->layout('layout') ?>

<?php $this->start('pageTitle') ?> | Documentation<?php $this->end() ?>

<?php $this->start('main') ?>
    <?php $this->insert('partials/small-header', ['title' => 'Documentation']) ?>

    <section id="one" class="wrapper">
        <div class="inner alt">
            <section class="spotlight text-only">
                <div class="content">
                    <div class="row">
                        <div class="3u 12u$(medium) side-menu-container">
                            <?php $this->insert('documentation/partials/side-menu') ?>
                        </div>
                        <div class="9u 12u$(medium) side-menu-contents">
                            <?php if ($this->section('documentationContent')): ?>
                                <?= $this->section('documentationContent') ?>
                            <?php else: ?>
                                <header>
                                    <h3>Getting started</h3>
                                </header>
                                <p>Shlink is a URL shortener which provides both a <a href="<?= $this->url('template', ['slug' => 'api-docs']) ?>">REST</a> and CLI interfaces to interact with it.</p>
                                <p>There are a couple of ways to install and run it, depending on your needs and resources.</p>
                                <ul>
                                    <li>You can run Shlink in a container-based infrastructure, using the <a href="<?= $this->url('documentation-section', ['slug' => 'install-docker-image']) ?>">docker image</a>.</li>
                                    <li>
                                        Alternatively you can <a href="<?= $this->url('documentation-section', ['slug' => 'install-dist-file']) ?>">download a dist file</a> to host it in your machine and serve it with:
                                        <ul>
                                            <li><a href="<?= $this->url('documentation-section', ['slug' => 'serve-with-swoole']) ?>">A non-blocking swoole server</a>.</li>
                                            <li><a href="<?= $this->url('documentation-section', ['slug' => 'classic-web-server']) ?>">A classic web server</a> (like Apache or Nginx).</li>
                                        </ul>
                                    </li>
                                </ul>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </section>
<?php $this->end() ?>
