<?php $this->layout('layout') ?>

<?php $this->start('main') ?>
    <?php $this->insert('partials/header') ?>

    <section id="one" class="wrapper">
        <div class="inner alt">
            <section class="spotlight">
                <div class="image">
                    <div class="fake-browser-ui">
                        <div class="frame">
                            <span class="close"></span>
                            <span class="minimize"></span>
                            <span class="maximize"></span>
                        </div>

                        <img src="/images/shlink-cli-cropped.gif" alt="Command line interface" />
                    </div>
                </div>
                <div class="content">
                    <h3>Command line interface</h3>
                    <p>Generate and manage short URLs from the command line.<br>List short codes, see visits or get the URL behind a short code.</p>
                </div>
            </section>

            <section class="spotlight">
                <div class="image">
                    <div class="fake-browser-ui">
                        <div class="frame">
                            <span class="close"></span>
                            <span class="minimize"></span>
                            <span class="maximize"></span>
                        </div>

                        <img src="/images/shlink-rest-cropped.gif" alt="REST API" />
                    </div>
                </div>
                <div class="content">
                    <h3>REST API</h3>
                    <p>Access your shortened URLs from anywhere.<br>Simple authentication and easy to integrate.</p>
                </div>
            </section>

            <section class="spotlight">
                <div class="image">
                    <div class="fake-browser-ui">
                        <div class="frame">
                            <span class="close"></span>
                            <span class="minimize"></span>
                            <span class="maximize"></span>
                        </div>

                        <img src="/images/shlink-web-client.gif" alt="Shlink web client" />
                    </div>
                </div>
                <div class="content">
                    <h3>Progressive web application</h3>
                    <p>Manage shlink using this beautiful and intuitive <a target="_blank" href="https://app.shlink.io">progressive web application</a>, or build your own.</p>
                </div>
            </section>

            <section class="special">
                <p>Shlink will track all the visits to your short URLs, saving detailed information and then transparently redirecting the visitor to the long URL:</p>
                <ul class="icons labeled">
                    <li><span class="icon fa-arrow-circle-o-right"><span class="label">Referer</span></span></li>
                    <li><span class="icon fa-laptop"><span class="label">Remote IP address</span></span></li>
                    <li><span class="icon fa-globe"><span class="label">Location of the visitor</span></span></li>
                    <li><span class="icon fa-chrome"><span class="label">User agent</span></span></li>
                </ul>
            </section>

            <section class="special">
                <header>
                    <h4>What makes Shlink different</h4>
                    <p>Shlink adds a lot of features which are not usually available in other free services.</p>
                </header>
                <ul class="actions">
                    <li>
                        <a href="<?= $this->url('template', ['slug' => 'features']) ?>"
                           class="button special icon fa-bolt">Features</a>
                    </li>
                </ul>
            </section>
        </div>
    </section>

    <!-- Three -->
    <section class="wrapper style2 special">
        <header class="major">
            <h2>Why shlink?</h2>
            <p>The name is an abbreviation for "short link", but if you get the words "shrink" and "link" together, the result is <b>shlink</b> too.<br>It is also the sound made by a sword being unsheathed.</p>
        </header>
        <p>
            Shlink is a PHP-based open source project, distributed under the <a href="https://opensource.org/licenses/MIT" target="_blank">MIT</a> license and hosted on <a href="https://github.com/shlinkio/shlink" target="_blank">Github</a>.<br>
            It is built with cutting edge technologies, such as <a href="https://docs.zendframework.com/zend-expressive/" target="_blank">Zend Expressive</a>, <a href="http://www.doctrine-project.org/projects/orm.html" target="_blank">Doctrine</a> or <a href="http://symfony.com/doc/current/components/console.html" target="_blank">Symfony</a>.
        </p>
    </section>
<?php $this->end() ?>
