<?php $this->layout('layout') ?>

<?php $this->start('main') ?>
    <?php $this->insert('partials/small-header') ?>

    <section id="three" class="wrapper style3 special">
        <header class="major">
            <h2>Installation</h2>
        </header>
    </section>
    <section id="one" class="wrapper">
        <div class="inner alt">
            <section class="spotlight text-only">
                <div class="content">
                    <p>Shlink is a web application built with PHP. It shouldn't be hard to install, but you have to follow these steps.</p>
                    <header>
                        <h4>Requirements</h4>
                    </header>
                    <ul>
                        <li>PHP 7.2 or greater with JSON, APCu, intl, curl, PDO and gd extensions enabled.</li>
                        <li>MySQL, PostgreSQL or SQLite.</li>
                        <li>The <a href="https://www.swoole.co.uk/" target="_blank">swoole</a> PHP extension or the web server of your choice with PHP integration (Apache or Nginx).</li>
                    </ul>
                </div>
            </section>
            <section class="spotlight text-only">
                <div class="content">
                    <header>
                        <h4>Install using a dist file</h4>
                    </header>
                    <ul>
                        <li>
                            Download the latest distributable file and decompress it at the location of your choice
                            <ul class="actions" style="text-align: center; margin: 1em 0;">
                                <li>
                                    <a href="https://github.com/shlinkio/shlink/releases/latest"
                                       target="_blank" class="button special icon fa-download download-shlink-btn">Download</a>
                                </li>
                            </ul>
                        </li>
                        <li>Create an empty database (not necessary if you are going to use SQLite).</li>
                        <li>
                            Setup the application by running the <code>bin/install</code> script. It will guide you through the installation process.
                        </li>
                        <li>Recursively grant write permissions to the <code>data</code> directory.</li>
                        <li>
                            Optionally, you can create a symlink to the <code>bin/cli</code> script in a folder which is in your path.<br>
                            For example <code>/usr/local/bin</code> for linux systems. This will allow you to easily run shlink from anywhere in the command line.
                        </li>
                        <li>Generate your first API key by running <code>bin/cli api-key:generate</code>. You will need the key in order to interact with shlink's API.</li>
                        <li>Finally access to <a href="https://app.shlink.io" target="_blank">https://app.shlink.io</a> and configure your server to start creating short URLs.</li>
                    </ul>
                </div>
            </section>
            <section class="spotlight text-only">
                <div class="content">
                    <header>
                        <h4>Install using a docker image</h4>
                    </header>
                    <p>If you want to deploy shlink in a container-based infrastructure, you can just use the official <a target="_blank" href="https://github.com/shlinkio/shlink-docker-image">docker image</a>.</p>
                    <p>Once deployed, you still need to run <code>docker exec -it shlink_container shlink api-key:generate</code> in order to generate the first API key.</p>
                </div>
            </section>
            <section class="spotlight text-only">
                <div class="content">
                    <header>
                        <h4>Virtual hosts</h4>
                        <p>
                            If you are serving shlink with a web server, you will need to configure the virtual hosts.
                            <br><br>
                            These are samples for the most used web servers.
                        </p>
                    </header>
                    <b>Nginx</b>
                    <pre>
                        <code>server {
    server_name doma.in;
    listen 80;
    root /path/to/shlink/public;
    index index.php;
    charset utf-8;

    location / {
        try_files $uri $uri/ /index.php$is_args$args;
    }

    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/var/run/php/php7.2-fpm.sock;
        fastcgi_index index.php;
        include fastcgi.conf;
    }

    location ~ /\.ht {
        deny all;
    }
}</code>
                    </pre>
                    <b>Apache</b>
                    <pre>
                        <code>&lt;VirtualHost *:80&gt;
    ServerName doma.in
    DocumentRoot &quot;/path/to/shlink/public&quot;

    &lt;Directory &quot;/path/to/shlink/public&quot;&gt;
        Options FollowSymLinks Includes ExecCGI
        AllowOverride all
        Order allow,deny
        Allow from all
    &lt;/Directory&gt;
&lt;/VirtualHost&gt;</code>
                    </pre>
                </div>
            </section>
            <section class="spotlight text-only">
                <div class="content">
                    <header>
                        <h4>Shlink with swoole service</h4>
                        <p>
                            If you want to server shlink with swoole, you should create a daemon script, in <code>/etc/init.d/shlink_swoole</code>.
                            <br><br>
                            You can use this sample, replacing <code>/path/to/shlink</code> by the path to your shlink installation:
                        </p>
                    </header>
                    <pre>
                        <code>#!/bin/bash
### BEGIN INIT INFO
# Provides:          shlink_swoole
# Required-Start:    $local_fs $network $named $time $syslog
# Required-Stop:     $local_fs $network $named $time $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       Shlink non-blocking server with swoole
### END INIT INFO

SCRIPT=/path/to/shlink/vendor/bin/zend-expressive-swoole\ start
RUNAS=root

PIDFILE=/var/run/shlink_swoole.pid
LOGDIR=/var/log/shlink
LOGFILE=${LOGDIR}/shlink_swoole.log

start() {
  if [[ -f "$PIDFILE" ]] && kill -0 $(cat "$PIDFILE"); then
    echo 'Shlink with swoole already running' >&2
    return 1
  fi
  echo 'Starting shlink with swoole' >&2
  mkdir -p "$LOGDIR"
  touch "$LOGFILE"
  local CMD="$SCRIPT &> \"$LOGFILE\" & echo \$!"
  su -c "$CMD" $RUNAS > "$PIDFILE"
  echo 'Shlink started' >&2
}

stop() {
  if [[ ! -f "$PIDFILE" ]] || ! kill -0 $(cat "$PIDFILE"); then
    echo 'Shlink with swoole not running' >&2
    return 1
  fi
  echo 'Stopping shlink with swoole' >&2
  kill -15 $(cat "$PIDFILE") && rm -f "$PIDFILE"
  echo 'Shlink stopped' >&2
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
esac</code>
                    </pre>

                    <p>Then run these commands to enable the service and start it:</p>

                    <ul>
                        <li><code>sudo chmod +x /etc/init.d/shlink_swoole</code></li>
                        <li><code>sudo update-rc.d shlink_swoole defaults</code></li>
                        <li><code>sudo update-rc.d shlink_swoole enable</code></li>
                        <li><code>/etc/init.d/shlink_swoole start</code></li>
                    </ul>

                    <p>After that, you should be able to access shlink on port 8080. The service will be automatically run at system start-up, and all access logs will be written in <code>/var/log/shlink/shlink_swoole.log</code></p>
                </div>
            </section>
            <section class="spotlight text-only">
                <div class="content">
                    <header>
                        <h4>Long-running tasks</h4>
                    </header>

                    <p>Resolving the IP of a visitor in order to get its location involves performing a request to an external service, which gets time. For this reason, this task is not done in real time.</p>
                    <p>You can manually run the command <code>visit:process</code> which will process all the IPs from visits.</p>
                    <p>Alternatively, you could create an scheduled task which automatically runs that command so that the information is updated periodically.</p>
                    <p>This is an example cron job that could be created under a Unix system. It will run the command every hour, processing all pending IP addresses:</p>
                    <p><code>0 * * * * /path/to/shlink/bin/cli visit:process -q</code></p>

                    <p>Something similar happens with page previews. Shlink is capable of generating the preview of a page behind a short code by appending the <b>/preview</b> path to a short URL. For example, <b>https://doma.in/abc123/preview</b>.</p>
                    <p>If you access that URL, the image will be generated and cached, but the first time, the request will take a little bit more time.</p>
                    <p>In order to prevent this, you can use the command <code>shortcode:process-previews</code>, which will generate all missing previews so that any later web request is faster</p>
                    <p>This command can be configured for a cron job too:</p>
                    <p><code>30 * * * * /path/to/shlink/bin/cli shortcode:process-previews -q</code></p>
                </div>
            </section>
        </div>
    </section>
<?php $this->end() ?>
