<!DOCTYPE HTML>
<html>
    <head>
        <title>Shlink - The URL shortener</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="A self-hosted and PHP-based URL shortener application with CLI and REST interfaces">
        <meta name="theme-color" content="#4696e5">

        <!-- build:css /assets/css/main.min.css?v= -->
        <link rel="stylesheet" href="/assets/css/font-awesome.min.css">
        <link rel="stylesheet" href="/assets/css/highlightjs-github.min.css">
        <link rel="stylesheet" href="/assets/css/main.css">
        <!-- /build -->
    </head>
    <body id="top">
        <?php $this->insert('partials/menu') ?>

        <?= $this->section('main', '') ?>

        <!-- Footer -->
        <footer id="footer">
            <ul class="icons">
                <li><a href="https://github.com/shlinkio/shlink" target="_blank" class="icon fa-github"><span class="label">Twitter</span></a></li>
                <li><a href="https://twitter.com/shlinkio" target="_blank" class="icon fa-twitter"><span class="label">Twitter</span></a></li>
                <li><a href="<?= $this->config('donate')['url'] ?>" target="_blank" class="icon fa-paypal"><span class="label">Donate</span></a></li>
            </ul>
            <p class="copyright">&copy; <?= date('Y') ?> Shlink, by <a href="https://www.alejandrocelaya.com" target="_blank">Alejandro Celaya</a> - Template from <a href="http://html5up.net">HTML5 UP</a></p>
        </footer>

        <!-- build:js /assets/js/main.min.js?v= -->
        <script src="/assets/js/jquery.min.js"></script>
        <script src="/assets/js/jquery.scrolly.min.js"></script>
        <script src="/assets/js/highlight.pack.js"></script>
        <script src="/assets/js/skel.min.js"></script>
        <script src="/assets/js/main.js"></script>
        <!-- /build -->

        <script>
            (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
                    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
            })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

            ga('create', 'UA-38351554-5', 'auto');
            ga('send', 'pageview');
        </script>
    </body>
</html>
